name: stun
description: "A new Flutter project."
version: 1.0.0
homepage: https://github.com/halifox/dart_stun

environment:
  sdk: ^3.6.0

dependencies:
  bit_buffer:
#    path: C:\Users\user\AndroidStudioProjects\dart_bit_buffer
    git:
      url: https://github.com/halifox/dart_bit_buffer
      ref: 1.0.6
dev_dependencies:
  test: 1.25.14
